---
title: "ISRS Question Answers and Testing"
output: html_notebook
---
######################################
Exercises 2.2 and 2.5
######################################
Problem 2.2:
Of the 34 patients in the control group, 4 were alive at the end of the study. Of the 69 patients in
the treatment group, 24 were alive. The contingency table below summarizes these results.
(a) What proportion of patients in the treatment group and what proportion of patients in the
control group died?
```{r}

```


(b) One approach for investigating whether or not the treatment is effective is to use a random-
ization technique.

i. What are the claims being tested? Use the same null and alternative hypothesis notation
used in the section.

ii. The paragraph below describes the set up for such approach, if we were to do it with-
out using statistical software. Fill in the blanks with a number or phrase, whichever is appropriate.
We write alive on cards representing patients who were alive at the end of the study, and dead on cards representing patients who were not. Then, we shuffle these cards and split them into two groups:
one group of size representing treatment, and another group of size representing control. We calculate the difference between the proportion of dead cards in the treatment and control groups (treatment -
control) and record this value. We repeat this many times to build a distribution
centered at . Lastly, we calculate the fraction of simulations where
the simulated differences in proportions are . If this fraction is low,
we conclude that it is unlikely to have observed such an outcome by chance and
that the null hypothesis should be rejected in favor of the alternative.

iii. What do the simulation results shown below suggest about the effectiveness of the trans-
plant program?


########################################
Exercise 5.2 
For figure 1: the data does not have a direct linear trend. It has non-constant variability so it is not fit for linear regression. 

For figure 2: the data shows a linear trend with constant variability but is has however the residuals are not normal. Residuals are normal if plotting the residuals forms a straight line 

Book ans:
(a) The residual plot will show randomly
distributed residuals around 0. The variance is
also approximately constant. 
(b) The residuals
will show a fan shape, with higher variability for
smaller x. There will also be many points on the
right above the line. There is trouble with the
model being fit here.

Exercise 5.9:
1,302 UCLA students were asked to fill out a survey where they were
asked about their height, fastest speed they have ever driven, and gender. The scatterplot on the
left displays the relationship between height and fastest speed, and the scatterplot on the right
displays the breakdown by gender in this relationship.
(a) Describe the relationship between height and fastest speed. 
The relationship does not seem linear
(b) Why do you think these variables are positively associated?
(c) What role does gender play in the relationship between height and fastest driving speed?
Ans: 
(a) The relationship is positive, weak, and
possibly linear. However, there do appear to
be some anomalous observations along the left
where several students have the same height
that is notably far from the cloud of the other
points. Additionally, there are many students
who appear not to have driven a car, and they are represented by a set of points along the bot-
tom of the scatterplot. 
(b) There is no obvious explanation why simply being tall should lead a person to drive faster. However, one confounding factor is gender. Males tend to be taller than females on average, and personal experi-
ences (anecdotal) may suggest they drive faster. If we were to follow-up on this suspicion, we
would find that sociological studies confirm this
suspicion. 
(c) Males are taller on average and
they drive faster. The gender variable is indeed
an important confounding variable.












