---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
ratings %>% head(10)
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=26

ratings %>% 
  ggplot(aes(x=rating)) +       
  geom_histogram(binwidth = 0.5) + 
  scale_y_continuous() +
  labs(x="Rating", y="Number of ratings")

```

## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean and number of ratings
# hint: use the n() function for easy counting within a group
popularity_data <- ratings %>% 
  group_by(movie_id) %>%  
  summarize(rating_count = n(), rating_mean = mean(rating)) %>% 
  select(movie_id, rating_mean, rating_count)
popularity_data


```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
# hint: try scale_x_log10() for a logarithmic x axis
popularity_data %>% 
  ggplot(aes(x=rating_count)) + 
  geom_histogram() + 
  scale_x_log10() 
```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=28
# hint: try geom_histogram and geom_density
popularity_data %>% 
  ggplot(aes(x=rating_mean))+
  geom_density(fill="blue",color="blue") +
  labs(x = "Mean Rating by Movie", y ="Density")

```

```{r cdf-movie-pop}
# rank movies by popularity and compute the cdf, or fraction of movies covered by the top-k moves https://speakerdeck.com/jhofman/modeling-social-data-lecture-2-introduction-to-counting?slide=30
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below

movie_count <-  nrow(ratings) - 1 

rank_by_movie <- 
  popularity_data %>% 
  arrange(desc(rating_count)) %>% 
  mutate(cumsum_count = cumsum(rating_count), percentage = cumsum_count/movie_count*100) 

rank_by_movie

# plot the CDF of movie popularity
rank_by_movie %>%  
  mutate(rank=rank(desc(rating_count))) %>% 
  ggplot(aes(x=rank, y= percentage)) + 
  geom_line(color="red") +
  labs(x="Movie Rank", y="CDF")

```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings
aggregate_by_user <- 
  ratings %>% 
  group_by(user_id) %>% 
  summarise(usr_rating_mean = mean(rating), usr_rating_count = n())
aggregate_by_user


```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here
aggregate_by_user %>%
  ggplot(aes(x=usr_rating_count)) + 
  geom_histogram(color="blue", fill ="blue") +
  scale_x_log10()

```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2 of this paper:
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. 
# As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).


rank_by_movie <- rank_by_movie %>%
mutate(movie_rank=rank(desc(rating_count)))
rank_by_movie

aggregate_by_user

mutated_aggregated_by_user <- 
  ratings %>% 
  group_by(user_id) %>% 
  mutate(usr_rating_mean = mean(rating), usr_rating_count = n())

movie_id_rank <- rank_by_movie %>% select(movie_id, movie_rank)

# this combines the popularity aggregate data and aggregate by user data
combined_df <- 
  movie_id_rank %>% 
  left_join(mutated_aggregated_by_user, by="movie_id") %>%
  group_by(user_id) %>% 
  arrange(user_id, desc(movie_rank)) 

top_rank_df <- 
  combined_df %>%
  top_n(n=1, wt=movie_rank)

top_rank_df

hundred_percent_satisfaction <- 
  top_rank_df %>% 
  arrange(movie_rank) %>% 
  group_by(movie_rank) %>% 
  summarise(rank_count= n()) %>%
  mutate(cumsum_ranking_count = cumsum(rank_count))  #%>%
#  ggplot(aes(x=movie_rank, y=cumsum_ranking_count)) +
#  geom_line()



Nintypct_satisfaction <- 
  combined_df %>%
  summarize(quants = quantile(movie_rank, probs = 0.9)) %>%
  arrange(quants) %>% 
  group_by(quants) %>%
  summarise(quant_count = n()) %>%
  mutate(cumsum_quant = cumsum(quant_count))

Nintypct_satisfaction



joined_plots <- 
  ggplot() +
  geom_line(data=hundred_percent_satisfaction,aes(x=movie_rank, y=cumsum_ranking_count)) +
  geom_line(data = Nintypct_satisfaction, aes(x=quants, y = cumsum_quant), color ="blue") +
  labs(x="Movie rank", y="User satisfaction percentage")

joined_plots

```
